<?php

$session = new \Zend\Session\Container();

if (!empty($session['samlUserdata'])) {
    $attributes = $session['samlUserdata'];
    printf('You have the following attributes:<br />');
    printf('<table><thead><th>Name</th><th>Values</th></thead><tbody>');
    foreach ($attributes as $attributeName => $attributeValues) {
        printf('<tr><td>%s</td><td>', \Zend\Filter\StaticFilter::execute($attributeName, 'HtmlEntities'));
        printf($this->htmlList($attributeValues));
        printf('</td></tr>');
    }
    printf('</tbody></table>');
    if (!empty($session['IdPSessionIndex'])) {
        printf('<p>The SessionIndex of the IdP is: %s</p>', $session['IdPSessionIndex']);
    }
} else {
    printf('<p>You don\'t have any attribute</p>');
}
?>

<p><a href="<?= $this->url('slo') ?>">Logout</a></p>
